export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  FACILITIES: '/facilities',
  TRADITIONS: '/traditions',
  RIVALRY: '/rivalry',
  ALUMNI: '/alumni',
  NEWS: '/news',
  EVENTS: '/events',
  GALLERY: '/gallery',
  ADMISSIONS: '/admissions',
  CONTACT: '/contact',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  DASHBOARD_RESIDENT: '/dashboard/resident',
  DASHBOARD_ALUMNI: '/dashboard/alumni',
  DASHBOARD_ADMIN: '/dashboard/admin',
  SETTINGS: '/settings',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  ACCESSIBILITY: '/accessibility',
  COOKIES: '/cookies',
  OFFLINE: '/offline',
} as const;

export const API_ROUTES = {
  MAINTENANCE: '/api/maintenance',
  BOOKINGS: '/api/bookings',
  DONATIONS: '/api/donations',
  NEWSLETTER: '/api/newsletter',
  MENTORSHIP: '/api/mentorship',
  EVENTS: '/api/events',
  NEWS: '/api/news',
  GALLERY: '/api/gallery',
  AUTH: '/api/auth',
  USERS: '/api/users',
} as const;

export const EXTERNAL_URLS = {
  KNUST_MAIN: 'https://www.knust.edu.gh',
  ACCOMMODATION_PORTAL: 'https://accommodation.knust.edu.gh',
  STUDENT_PORTAL: 'https://apps.knust.edu.gh/students',
  ADMISSIONS_PORTAL: 'https://apps.knust.edu.gh/admissions',
  PAYMENT_PORTAL: 'https://pay.knust.edu.gh',
  AIM_APP_ANDROID: 'https://play.google.com/store/apps/details?id=gh.edu.knust.aim',
  AIM_APP_IOS: 'https://apps.apple.com/us/app/knust-aim/id1632229714',
  FOCUS_FM: 'https://focusfmknust.com',
  CONTINENTAL_RADIO_ARCHIVE: 'https://focusfmknust.wordpress.com',
  ONEDRIVE_GH: 'https://oneclickghana.com/conti-unity-hall-anthem-1/',
  GITHUB_REPO: 'https://github.com/unity-hall-knust/unity-hall-website',
} as const;